# Site settings
title: Erik Herberg
baseurl: "" 

# Build settings
markdown: kramdown

# Assets Pipeline
assets:
  sources:
    - _assets
    - _assets/fonts
    - _assets/stylesheets
    - _assets/documents
    - _assets/images

exclude: [Rakefile]